export const Dummy_Tasks = [
  {
    id: 't1',
    userId: 'u1',
    title: 'Master Angular',
    summary:
      'Learn all the basic and advanced features of Angular & how to apply them.',
    dueDate: '2025-12-31',
  },
  {
    id: 't2',
    userId: 'u3',
    title: 'Build first prototype',
    summary: 'Build a first prototype of the online shop website',
    dueDate: '2024-05-31',
  },
  {
    id: 't3',
    userId: 'u3',
    title: 'Prepare issue template',
    summary:
      'Prepare and describe an issue template which will help with project management',
    dueDate: '2024-06-15',
  },
  {
    id: 't4',
    userId: 'u2',
    title: 'Create logo',
    summary: 'Create a new logo for the company',
    dueDate: '2024-07-15',
  },
  {
    id: 't5',
    userId: 'u4',
    title: 'Create logo',
    summary: 'Create a new logo for the company',
    dueDate: '2024-07-15',
  },
  {
    id: 't6',
    userId: 'u4',
    title: 'Create logo',
    summary: 'Create a new logo for the company',
    dueDate: '2024-07-15',
  },
  {
    id: 't7',
    userId: 'u5',
    title: 'Create logo',
    summary: 'Create a new logo for the company',
    dueDate: '2024-07-15',
  },
  {
    id: 't8',
    userId: 'u6',
    title: 'Create logo',
    summary: 'Create a new logo for the company',
    dueDate: '2024-07-15',
  },
  {
    id: 't9',
    userId: 'u1',
    title: 'Create logo',
    summary: 'Create a new logo for the company',
    dueDate: '2024-07-15',
  },
  {
    id: 't10',
    userId: 'u2',
    title: 'Create logo',
    summary: 'Create a new logo for the company',
    dueDate: '2024-07-15',
  },
  {
    id: 't11',
    userId: 'u3',
    title: 'Create logo',
    summary: 'Create a new logo for the company',
    dueDate: '2024-07-15',
  },
  {
    id: 't12',
    userId: 'u4',
    title: 'Create logo',
    summary: 'Create a new logo for the company',
    dueDate: '2024-07-15',
  },
  {
    id: 't13',
    userId: 'u5',
    title: 'Create logo',
    summary: 'Create a new logo for the company',
    dueDate: '2024-07-15',
  },
  {
    id: 't14',
    userId: 'u6',
    title: 'Create logo',
    summary: 'Create a new logo for the company',
    dueDate: '2024-07-15',
  },
  {
    id: 't15',
    userId: 'u1',
    title: 'Create logo',
    summary: 'Create a new logo for the company',
    dueDate: '2024-07-15',
  },
]
